// <auto-generated />
using System;
using IclPaths.API.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IclPaths.API.Migrations
{
    [DbContext(typeof(IclPathsDbContext))]
    [Migration("20260402172946_Adding Images Table")]
    partial class AddingImagesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IclPaths.API.Models.DomainModels.IclPathsDbModels.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("IclPaths.API.Models.DomainModels.IclPathsDbModels.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileExtension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("IclPaths.API.Models.DomainModels.IclPathsDbModels.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "IS-1",
                            Name = "Capital Region (Höfuðborgarsvæðið)",
                            RegionImageUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Capital%20Region%2C%20Iceland%20-%20panoramio%20(15).jpg"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "IS-2",
                            Name = "Southern Peninsula (Suðurnes)",
                            RegionImageUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Southern%20Peninsula%20Region%2C%20Iceland%20-%20panoramio.jpg"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Code = "IS-3",
                            Name = "Western Region (Vesturland)",
                            RegionImageUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Western%20Region%2C%20Iceland%20-%20panoramio.jpg"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Code = "IS-4",
                            Name = "Westfjords (Vestfirðir)",
                            RegionImageUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Westfjords%20Region%2C%20Iceland%20-%20panoramio%20(5).jpg"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Code = "IS-5",
                            Name = "Northwestern Region (Norðurland vestra)",
                            RegionImageUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Northwestern%20Region%2C%20Iceland%20-%20panoramio.jpg"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Code = "IS-6",
                            Name = "Northeastern Region (Norðurland eystra)",
                            RegionImageUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Northeastern%20Region%2C%20Iceland%20-%20panoramio%20(24).jpg"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Code = "IS-7",
                            Name = "Eastern Region (Austurland)",
                            RegionImageUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Eastern%20Region%2C%20Iceland%20-%20panoramio%20(1).jpg"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Code = "IS-8",
                            Name = "Southern Region (Suðurland)",
                            RegionImageUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/South%2C%20Iceland%20-%20panoramio.jpg"
                        });
                });

            modelBuilder.Entity("IclPaths.API.Models.DomainModels.IclPathsDbModels.WalkPath", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Paths");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "Iconic multi-day trek through geothermal valleys, mountains and glaciers.",
                            DifficultyId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            LengthInKm = 55.0,
                            Name = "Laugavegur Trail",
                            PathImageUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Laugavegur_trail.jpg",
                            RegionId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Description = "Mountain trail between two glaciers with waterfalls and volcanic landscapes.",
                            DifficultyId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            LengthInKm = 25.0,
                            Name = "Fimmvörðuháls Pass",
                            PathImageUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Fimmvorduhals_hike.jpg",
                            RegionId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Description = "Hike to Iceland’s second-highest waterfall with river crossings and caves.",
                            DifficultyId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            LengthInKm = 7.5,
                            Name = "Glymur Waterfall Hike",
                            PathImageUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Glymur_waterfall_hike.jpg",
                            RegionId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Description = "Remote Arctic wilderness hike with cliffs, foxes and dramatic coastline.",
                            DifficultyId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            LengthInKm = 15.0,
                            Name = "Hornstrandir Coastal Trail",
                            PathImageUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Hornstrandir_coast.jpg",
                            RegionId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Description = "Popular hike near Reykjavík with panoramic views over the capital region.",
                            DifficultyId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            LengthInKm = 6.5,
                            Name = "Mt. Esja Trail",
                            PathImageUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Mount_Esja_hike.jpg",
                            RegionId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Description = "Easy walk along Europe’s most powerful waterfall in a volcanic canyon.",
                            DifficultyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            LengthInKm = 3.0,
                            Name = "Dettifoss River Trail",
                            PathImageUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Dettifoss_hike.jpg",
                            RegionId = new Guid("66666666-6666-6666-6666-666666666666")
                        });
                });

            modelBuilder.Entity("IclPaths.API.Models.DomainModels.IclPathsDbModels.WalkPath", b =>
                {
                    b.HasOne("IclPaths.API.Models.DomainModels.IclPathsDbModels.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IclPaths.API.Models.DomainModels.IclPathsDbModels.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
